const crypto = require('crypto');
const { getStore } = require('@netlify/blobs');
const REPO = process.env.GITHUB_REPO || 'narayanbhandari58/narayanbhandari';
const BRANCH = process.env.GITHUB_BRANCH || 'main';
const TOKEN = process.env.GITHUB_TOKEN;
const SECRET = process.env.ADMIN_JWT_SECRET;
const GH = 'https://api.github.com';
const json=(statusCode,body)=>({statusCode,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS'},body:JSON.stringify(body)});
function b64(s){return Buffer.from(s).toString('base64url')};function unb(s){return Buffer.from(s,'base64url').toString()};
function verify(t){if(!t||!SECRET)return null;try{const [h,p,s]=t.split('.');const good=b64(crypto.createHmac('sha256',SECRET).update(`${h}.${p}`).digest())===s;const o=JSON.parse(unb(p));return good&&o.exp>=Date.now()/1000?o:null}catch{return null}}
function isAdmin(e){return verify((e.headers?.authorization||'').replace(/^Bearer\s+/i,''))}
async function gh(path,opt={}){if(!TOKEN)throw Error('GITHUB_TOKEN is not configured');const r=await fetch(`${GH}/repos/${REPO}/contents/${path}`,{...opt,headers:{Authorization:`Bearer ${TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json();if(!r.ok)throw Error(d.message||'GitHub request failed');return d}
async function readData(){const d=await gh('exam-data.json');return{sha:d.sha,data:JSON.parse(Buffer.from(d.content.replace(/\n/g,''),'base64').toString('utf8'))}}
async function writeData(data,sha){return gh('exam-data.json',{method:'PUT',body:JSON.stringify({message:'Update Loksewa exam question bank',content:Buffer.from(JSON.stringify(data,null,2)).toString('base64'),branch:BRANCH,sha})})}
function publicQuestion(q){return{id:q.id,examIds:q.examIds,section:q.section,unit:q.unit,subject:q.subject,topic:q.topic,level:q.level,type:q.type,q:q.q,options:q.options}}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function blobStore(){const siteID=process.env.NETLIFY_SITE_ID||process.env.SITE_ID;const token=process.env.NETLIFY_API_TOKEN||process.env.NETLIFY_AUTH_TOKEN||process.env.NETLIFY_TOKEN;return siteID&&token?getStore('exam-attempts',{siteID,token}):getStore('exam-attempts')}
async function attempts(){const store=blobStore(),out=[];let cursor;do{const r=await store.list(cursor?{cursor}:{});for(const b of (r.blobs||[])){try{const x=await store.get(b.key,{type:'json'});if(x)out.push(x)}catch{}}cursor=r.cursor}while(cursor);return out.sort((a,b)=>String(b.submittedAt).localeCompare(String(a.submittedAt)))}
function unitPlan(exam){return (exam.blueprint?.sections||[]).flatMap(s=>(s.units||[]).map(u=>({...u,sectionId:s.id,sectionTitle:s.title,sectionLevelDistribution:s.levelDistribution||null})))}
function blueprintReady(exam,bank){const plan=unitPlan(exam);if(!plan.length)return bank.length>=exam.questionCount;for(const u of plan){const n=bank.filter(q=>q.section===u.sectionId&&q.unit===u.id).length;if(n<u.questionCount)return false}for(const s of (exam.blueprint?.sections||[])){const d=s.levelDistribution;if(!d)continue;const q=bank.filter(x=>x.section===s.id);if((q.filter(x=>x.level==='level1').length<(d.level1||0))||(q.filter(x=>x.level==='level2').length<(d.level2||0)))return false}return true}
function selectPaper(exam,bank){const plan=unitPlan(exam);if(!plan.length)return shuffle(bank).slice(0,exam.questionCount);const selected=[];for(const section of (exam.blueprint?.sections||[])){const sectionBank=bank.filter(q=>q.section===section.id);const d=section.levelDistribution;let remaining1=d?.level1||0,remaining2=d?.level2||0;for(const u of (section.units||[])){const pool=shuffle(sectionBank.filter(q=>q.unit===u.id));if(!pool.length)continue;const need=u.questionCount;const l1=pool.filter(q=>q.level==='level1');const l2=pool.filter(q=>q.level==='level2');let take1=d?Math.max(0,Math.min(l1.length,remaining1,need-l2.length)):0;let take2=d?Math.max(0,Math.min(l2.length,remaining2,need-take1)):0;if(d&&take1+take2<need){const rest=shuffle([...l1.slice(take1),...l2.slice(take2),...pool.filter(q=>q.level!=='level1'&&q.level!=='level2')]).slice(0,need-take1-take2);selected.push(...shuffle([...l1.slice(0,take1),...l2.slice(0,take2),...rest]));}else selected.push(...shuffle([...l1.slice(0,take1),...l2.slice(0,take2)]));remaining1-=take1;remaining2-=take2}}return shuffle(selected).slice(0,exam.questionCount)}
exports.handler=async(event)=>{if(event.httpMethod==='OPTIONS')return json(204,{});try{const p=new URLSearchParams(event.rawQuery||'');const action=p.get('action')||'config';const body=event.body?JSON.parse(event.body):{};const {data}=await readData();
if(action==='config'){const exam=data.exams.find(x=>x.id===(p.get('exam')||body.examId)&&x.enabled!==false);if(!exam)return json(404,{error:'परीक्षा भेटिएन'});const bank=data.questions.filter(q=>q.examIds?.includes(exam.id));const ready=blueprintReady(exam,bank);const paper=ready?selectPaper(exam,bank):[];return json(200,{exam,blueprint:exam.blueprint||null,availableQuestions:bank.length,ready,questions:paper.map(publicQuestion)})}
if(action==='submit'){const exam=data.exams.find(x=>x.id===body.examId&&x.enabled!==false);if(!exam)return json(404,{error:'परीक्षा भेटिएन'});const bank=new Map(data.questions.filter(q=>q.examIds?.includes(exam.id)).map(q=>[q.id,q]));const answers=body.answers&&typeof body.answers==='object'?body.answers:{};const ids=Array.isArray(body.questionIds)?body.questionIds.slice(0,exam.questionCount):[];if(ids.length!==exam.questionCount)return json(409,{error:`यस परीक्षाका लागि ${exam.questionCount} प्रश्न चाहिन्छ। Blueprint अनुसार Question Bank पूरा भएपछि परीक्षा सुरु हुनेछ।`});let correct=0,wrong=0,skipped=0;const review=[];for(const id of ids){const q=bank.get(id);if(!q)continue;const raw=answers[id];const selected=Number.isInteger(raw)?raw:null;if(selected===null)skipped++;else if(selected===q.correct)correct++;else wrong++;review.push({id:q.id,q:q.q,options:q.options,selected,correct:q.correct,type:q.type,section:q.section||'',unit:q.unit||'',subject:q.subject,topic:q.topic,level:q.level||'',explanation:q.explanation||'',solution:q.solution||''})}if(review.length!==exam.questionCount)return json(409,{error:'Question Bank मा आवश्यक सबै प्रश्न उपलब्ध छैनन्।'});const score=Number((correct*Number(exam.positiveMark||1)-wrong*Number(exam.negativeMark||.2)).toFixed(2));const maxScore=review.length*Number(exam.positiveMark||1);const percent=maxScore?Number((score/maxScore*100).toFixed(2)):0;const result={attemptId:`attempt-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`,examId:exam.id,examTitle:exam.title,stage:exam.stage||'Stage-I',candidate:{name:String(body.name||'').slice(0,100),email:String(body.email||'').slice(0,160),whatsapp:String(body.whatsapp||'').slice(0,30)},submittedAt:new Date().toISOString(),correct,wrong,skipped,score,maxScore,percent,passed:percent>=Number(exam.passPercent||45),review};await blobStore().set(result.attemptId,JSON.stringify(result),{metadata:{examId:exam.id}});return json(200,{result})}
if(action==='admin-data'){if(!isAdmin(event))return json(401,{error:'Admin login आवश्यक छ'});return json(200,{data})}
if(action==='admin-history'||action==='admin-users'){if(!isAdmin(event))return json(401,{error:'Admin login आवश्यक छ'});const a=await attempts();if(action==='admin-users'){const m={};a.forEach(x=>{const c=x.candidate||{},k=c.email||c.whatsapp||c.name||x.attemptId;if(!m[k])m[k]={...c,attempts:0,last:x.submittedAt};m[k].attempts++;if(x.submittedAt>m[k].last)m[k].last=x.submittedAt});return json(200,{users:Object.values(m)})}return json(200,{attempts:a})}
if(action==='save-data'){if(!isAdmin(event))return json(401,{error:'Admin login आवश्यक छ'});if(!body.data||!Array.isArray(body.data.exams)||!Array.isArray(body.data.questions))return json(400,{error:'Exam data format गलत छ'});const cur=await readData();await writeData(body.data,cur.sha);return json(200,{ok:true,message:'Exam data सुरक्षित भयो'})}
return json(400,{error:'Unknown action'})}catch(e){console.error(e);return json(500,{error:e.message||'Exam API error'})}};
