const crypto=require('crypto');
const REPO=process.env.GITHUB_REPO||'narayanbhandari58/narayanbhandari';
const BRANCH=process.env.GITHUB_BRANCH||'main';
const TOKEN=process.env.GITHUB_TOKEN;
const SECRET=process.env.ADMIN_JWT_SECRET;
const GH='https://api.github.com';
const json=(statusCode,body)=>({statusCode,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS'},body:JSON.stringify(body)});
function b64(s){return Buffer.from(s).toString('base64url')}
function verify(t){if(!t||!SECRET)return null;try{const[h,p,s]=String(t).split('.');if(!h||!p||!s)return null;const ex=b64(crypto.createHmac('sha256',SECRET).update(h+'.'+p).digest());if(ex.length!==s.length||!crypto.timingSafeEqual(Buffer.from(ex),Buffer.from(s)))return null;const o=JSON.parse(Buffer.from(p,'base64url').toString());return o.sub&&o.exp>=Date.now()/1000?o:null}catch{return null}}
function admin(e){return verify((e.headers?.authorization||'').replace(/^Bearer\s+/i,''))}
async function gh(path,opt={}){if(!TOKEN)throw Error('GITHUB_TOKEN is not configured');const r=await fetch(GH+'/repos/'+REPO+'/contents/'+path,{...opt,headers:{Authorization:'Bearer '+TOKEN,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json();if(!r.ok)throw Error(d.message||'GitHub request failed');return d}
async function read(path){const m=await gh(path);if(typeof m.content==='string'&&m.content.trim())return{data:JSON.parse(Buffer.from(m.content,'base64').toString('utf8')),sha:m.sha};const r=await fetch(GH+'/repos/'+REPO+'/git/blobs/'+m.sha,{headers:{Authorization:'Bearer '+TOKEN,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});const d=await r.json();if(!r.ok||d.encoding!=='base64')throw Error('GitHub file पढ्न सकिएन');return{data:JSON.parse(Buffer.from(d.content.replace(/\s/g,''),'base64').toString('utf8')),sha:m.sha}}
async function write(path,data,sha,message){return gh(path,{method:'PUT',body:JSON.stringify({message,content:Buffer.from(JSON.stringify(data,null,2)).toString('base64'),branch:BRANCH,sha})})}
function path(exam,set){return 'sets/'+exam+'/set-'+String(set).padStart(2,'0')+'.json'}
function safeExam(id){return /^(kharidar|nasu|sakha-adhikrit)$/.test(String(id))}
function safeSet(n){return /^(?:[1-9]|10)$/.test(String(n))}
function validQuestion(q){return q&&String(q.q||q.question||'').trim()&&Array.isArray(q.options)&&q.options.length===4&&q.options.every(x=>String(x??'').trim())&&Number.isInteger(Number(q.correct))&&Number(q.correct)>=0&&Number(q.correct)<=3}
function cleanQuestion(q,exam){return {...q,id:String(q.id||('setq-'+Date.now()+'-'+crypto.randomBytes(3).toString('hex'))),examIds:[exam],setOnly:true,q:String(q.q||q.question||'').trim(),options:q.options.map(x=>String(x).trim()),correct:Number(q.correct),section:String(q.section||'').trim(),unit:String(q.unit||'').trim(),subject:String(q.subject||'').trim(),topic:String(q.topic||'').trim(),level:String(q.level||'level1'),type:String(q.type||'gk'),explanation:String(q.explanation||'').trim(),solution:String(q.solution||'').trim(),image:String(q.image||'').trim(),imageAlt:String(q.imageAlt||q.image_alt||'').trim(),passage:String(q.passage||'').trim(),figure:String(q.figure||q.data||'').trim()}}
function adminOnly(e){if(!admin(e))return json(401,{error:'Admin login आवश्यक छ'});return null}
exports.handler=async event=>{if(event.httpMethod==='OPTIONS')return json(204,{});try{
 const p=new URLSearchParams(event.rawQuery||''),a=p.get('action')||'list',body=event.body?JSON.parse(event.body):{};
 if(a==='list'){const idx=(await read('sets/index.json')).data;const names={kharidar:'खरिदार तयारी परीक्षा',nasu:'नायब सुब्बा तयारी परीक्षा','sakha-adhikrit':'शाखा अधिकृत तयारी परीक्षा'};return json(200,{exams:['kharidar','nasu','sakha-adhikrit'].map(id=>({exam:{id,title:names[id]},sets:(idx.sets||[]).filter(x=>x.examId===id)}))})}
 if(a==='get'){const id=String(p.get('exam')||''),n=String(p.get('set')||'');if(!safeExam(id)||!safeSet(n))return json(400,{error:'Set पहिचान गलत छ'});const s=(await read(path(id,n))).data;return json(200,{set:{...s,questions:s.questions.map(q=>{const x={...q};delete x.correct;return x})}})}
 if(a==='submit'){const id=String(body.examId||''),n=String(body.setId||'');if(!safeExam(id)||!safeSet(n))return json(400,{error:'Set पहिचान गलत छ'});const s=(await read(path(id,n))).data;const answers=body.answers&&typeof body.answers==='object'?body.answers:{};let correct=0,wrong=0,skipped=0;const review=s.questions.map(q=>{const v=Number.isInteger(answers[q.id])?answers[q.id]:null;if(v===null)skipped++;else if(v===q.correct)correct++;else wrong++;return{id:q.id,q:q.q||q.question,options:q.options,selected:v,correct:q.correct,type:q.type||'',format:q.format||'',section:q.section||'',unit:q.unit||'',subject:q.subject||'',topic:q.topic||'',level:q.level||'',image:q.image||q.imageUrl||q.image_url||'',imageAlt:q.imageAlt||q.image_alt||q.topic||'प्रश्नचित्र',passage:q.passage||'',figure:q.figure||'',data:q.data||'',explanation:q.explanation||'',solution:q.solution||''}});const score=Number((correct*Number(s.positiveMark||1)-wrong*Number(s.negativeMark||.2)).toFixed(2)),max=review.length*Number(s.positiveMark||1),percent=max?Number((score/max*100).toFixed(2)):0;return json(200,{result:{examId:id,setId:n,examTitle:s.title,candidate:{name:String(body.name||'').slice(0,100)},submittedAt:new Date().toISOString(),correct,wrong,skipped,score,maxScore:max,percent,passed:percent>=Number(s.passPercent||45),review}})}
 if(a==='admin-list'){const x=adminOnly(event);if(x)return x;const idx=(await read('sets/index.json')).data;const names={kharidar:'खरिदार तयारी परीक्षा',nasu:'नायब सुब्बा तयारी परीक्षा','sakha-adhikrit':'शाखा अधिकृत तयारी परीक्षा'};return json(200,{exams:['kharidar','nasu','sakha-adhikrit'].map(id=>({exam:{id,title:names[id]},sets:(idx.sets||[]).filter(x=>x.examId===id)}))})}
 if(a==='admin-get'){const x=adminOnly(event);if(x)return x;const id=String(p.get('exam')||''),n=String(p.get('set')||'');if(!safeExam(id)||!safeSet(n))return json(400,{error:'Set पहिचान गलत छ'});return json(200,{set:(await read(path(id,n))).data})}
 if(a==='admin-save'){const x=adminOnly(event);if(x)return x;const id=String(body.examId||''),n=String(body.setId||'');if(!safeExam(id)||!safeSet(n)||!validQuestion(body.question))return json(400,{error:'Set वा प्रश्नको विवरण गलत छ'});const fp=path(id,n),cur=await read(fp),s=cur.data,q=cleanQuestion(body.question,id);const i=body.question.id?s.questions.findIndex(x=>String(x.id)===String(body.question.id)):-1;if(i>=0)s.questions[i]=q;else s.questions.push(q);s.questionCount=s.questions.length;await write(fp,s,cur.sha,'Update Stable Set question');const idx=await read('sets/index.json');const item=(idx.data.sets||[]).find(x=>x.examId===id&&String(x.setId)===String(n).padStart(2,'0'));if(item){item.questionCount=s.questions.length;await write('sets/index.json',idx.data,idx.sha,'Update Stable Set metadata')}return json(200,{message:i>=0?'Set प्रश्न सम्पादन भयो।':'नयाँ Set प्रश्न थपियो।',set:s})}
 if(a==='admin-delete'){const x=adminOnly(event);if(x)return x;const id=String(body.examId||''),n=String(body.setId||''),qid=String(body.questionId||'');if(!safeExam(id)||!safeSet(n)||!qid)return json(400,{error:'Set वा प्रश्न पहिचान गलत छ'});const fp=path(id,n),cur=await read(fp),s=cur.data,old=s.questions.length;s.questions=s.questions.filter(q=>String(q.id)!==qid);if(s.questions.length===old)return json(404,{error:'प्रश्न भेटिएन'});if(!s.questions.length)return json(400,{error:'Set खाली बनाउन मिल्दैन'});s.questionCount=s.questions.length;await write(fp,s,cur.sha,'Delete Stable Set question');const idx=await read('sets/index.json');const item=(idx.data.sets||[]).find(x=>x.examId===id&&String(x.setId)===String(n).padStart(2,'0'));if(item){item.questionCount=s.questions.length;await write('sets/index.json',idx.data,idx.sha,'Update Stable Set metadata')}return json(200,{message:'Set प्रश्न हटाइयो।',set:s})}
 return json(400,{error:'Unknown action'});
}catch(e){console.error(e);return json(500,{error:e.message||'Set API error'})}};