/* =========================================
   NARAYAN BHANDARI — ADMIN CMS
   admin.html remains the single CMS entry point.
========================================= */
let posts=[];let editing=null;let imageRemoved=false;let tagList=[];
const $=s=>document.querySelector(s);
const token=()=>localStorage.getItem('nb_admin_token')||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(action,opt={}){const r=await fetch(`/.netlify/functions/api?action=${encodeURIComponent(action)}`,{...opt,headers:{'Content-Type':'application/json','Authorization':`Bearer ${token()}`,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function msg(m){const t=$('#toast');if(!t)return;t.textContent=m;t.style.display='block';clearTimeout(window.__nbToast);window.__nbToast=setTimeout(()=>t.style.display='none',2800)}
function renderTags(){const box=$('#tagBox'),input=$('#tags');if(!box||!input)return;box.querySelectorAll('.tag-item').forEach(x=>x.remove());tagList.forEach((tag,index)=>{const item=document.createElement('span');item.className='tag-item';item.innerHTML=`<span>${esc(tag)}</span><button type="button" aria-label="Remove tag">×</button>`;item.querySelector('button').onclick=()=>{tagList.splice(index,1);renderTags();input.focus()};box.insertBefore(item,input)})}
function addTag(v){v=String(v||'').replace(/,/g,'').trim();if(!v)return;if(!tagList.includes(v))tagList.push(v);if($('#tags'))$('#tags').value='';renderTags()}
function getTags(){const v=$('#tags')?.value.trim();if(v)addTag(v);return tagList.join(', ')}
function setTags(v){tagList=String(v||'').split(',').map(x=>x.trim()).filter(Boolean);if($('#tags'))$('#tags').value='';renderTags()}
function clearImagePreview(){if($('#imagePreview'))$('#imagePreview').innerHTML=''}
function showImagePreview(src,label='Featured Image preview'){const p=$('#imagePreview');if(!p||!src)return;p.innerHTML=`<div class="image-preview-card"><img src="${esc(src)}" alt="${esc(label)}"><div class="image-preview-info"><small>${esc(label)}</small><button type="button" class="btn btn-danger" id="removeImage">🗑 हटाउनुहोस्</button></div></div>`;$('#removeImage')?.addEventListener('click',()=>{if($('#image'))$('#image').value='';imageRemoved=true;clearImagePreview();msg('Featured Image हटाइयो')})}
function resetPost(){editing=null;imageRemoved=false;$('#postForm')?.reset();if($('#postId'))$('#postId').value='';if($('#formHeading'))$('#formHeading').textContent='नयाँ पोस्ट';clearImagePreview();tagList=[];renderTags()}
function updateCategoryFilter(){const s=$('#postCategoryFilter');if(!s)return;const old=s.value,c=[...new Set(posts.map(p=>String(p.category||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ne'));s.innerHTML='<option value="">सबै श्रेणी</option>'+c.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(c.includes(old))s.value=old}
function filteredPosts(){const q=String($('#postSearch')?.value||'').trim().toLocaleLowerCase();const c=$('#postCategoryFilter')?.value||'';const st=String($('#postStatusFilter')?.value||'').toLowerCase();return posts.filter(p=>{const h=[p.title,p.category,p.tags,p.content].map(x=>String(x||'').toLocaleLowerCase()).join(' ');const s=String(p.status||'').toLowerCase();return(!q||h.includes(q))&&(!c||String(p.category||'')===c)&&(!st||s===st)})}
function renderPosts(){const list=filteredPosts(),count=$('#postResultCount');if(count)count.textContent=`${list.length} / ${posts.length} पोस्ट`;const table=$('#table');if(!table)return;if(!list.length){table.innerHTML=posts.length?'<p>खोज/Filter अनुसार कुनै पोस्ट भेटिएन।</p>':'<p>कुनै पोस्ट छैन।</p>';return}table.innerHTML=list.map(p=>{const st=String(p.status||'').toLowerCase(),label=st==='published'?'प्रकाशित':st==='draft'?'ड्राफ्ट':(p.status||'स्थिति छैन');return`<article class="post-row"><div class="post-row-main"><div class="post-row-title-wrap"><b>${esc(p.title)}</b><span class="status status-${st==='published'?'published':st==='draft'?'draft':'other'}">${esc(label)}</span></div><small>${esc(p.category||'')} · ${p.created?new Date(p.created).toLocaleDateString('ne-NP'):''}</small></div><div class="post-actions"><button class="btn btn-outline" type="button" onclick="editPost('${esc(p.id)}')">सम्पादन</button><button class="btn btn-danger" type="button" onclick="deletePost('${esc(p.id)}')">मेटाउनुहोस्</button></div></article>`}).join('')}
async function loadPosts(){try{const d=await api('posts');posts=d.posts||[];updateCategoryFilter();renderPosts();updateStats()}catch(e){msg(e.message)}}
function updateStats(){const pub=posts.filter(p=>String(p.status).toLowerCase()==='published').length,draft=posts.filter(p=>String(p.status).toLowerCase()==='draft').length,cats=new Set(posts.map(p=>p.category).filter(Boolean));if($('#totalPosts'))$('#totalPosts').textContent=posts.length;if($('#publishedPosts'))$('#publishedPosts').textContent=pub;if($('#draftPosts'))$('#draftPosts').textContent=draft;if($('#totalCategories'))$('#totalCategories').textContent=cats.size;['nbTotal','nbPublished','nbDraft','nbCategories'].forEach((id,i)=>{const v=[posts.length,pub,draft,cats.size][i];if($('#'+id))$('#'+id).textContent=v})}
window.editPost=id=>{const p=posts.find(x=>x.id===id);if(!p)return;editing=p;imageRemoved=false;$('#postId').value=p.id;$('#title').value=p.title||'';$('#category').value=p.category||'';setTags(p.tags||'');$('#content').value=p.content||'';if($('#formHeading'))$('#formHeading').textContent='पोस्ट सम्पादन';if(p.featuredImage)showImagePreview(p.featuredImage,'हालको Featured Image');else clearImagePreview();if(window.tinymce&&tinymce.get('content'))tinymce.get('content').setContent(p.content||'');openWorkspace('posts');window.scrollTo({top:0,behavior:'smooth'})};
window.deletePost=async id=>{if(!confirm('यो पोस्ट मेटाउने?'))return;try{await api('delete',{method:'POST',body:JSON.stringify({id})});msg('पोस्ट मेटाइयो');await loadPosts()}catch(e){msg(e.message)}};
async function savePost(status){const title=$('#title')?.value.trim(),category=$('#category')?.value||'',tags=getTags(),content=window.tinymce?.get('content')?.getContent()||$('#content')?.value||'';if(!title||!content){msg('शीर्षक र सामग्री आवश्यक छ');return}try{let featuredImage=editing?.featuredImage||'';const file=$('#image')?.files?.[0];if(file){const b=await file.arrayBuffer();let bin='';new Uint8Array(b).forEach(x=>bin+=String.fromCharCode(x));const d=await api('upload',{method:'POST',body:JSON.stringify({name:file.name,mime:file.type,data:btoa(bin)})});featuredImage=d.url}else if(imageRemoved)featuredImage='';const d=await api('save',{method:'POST',body:JSON.stringify({id:editing?.id,title,category,tags,content,featuredImage,status})});msg(d.message||'सेभ भयो');resetPost();await loadPosts()}catch(e){msg(e.message)}}
function setupPostEditor(){const tags=$('#tags');tags?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===','||e.key===' '){const v=tags.value.trim();if(v){e.preventDefault();addTag(v)}}});tags?.addEventListener('blur',()=>{if(tags.value.trim())addTag(tags.value)});$('#image')?.addEventListener('change',()=>{const f=$('#image').files?.[0];if(!f)return;if(!f.type.startsWith('image/')){msg('कृपया image file मात्र छान्नुहोस्');$('#image').value='';return}imageRemoved=false;showImagePreview(URL.createObjectURL(f),f.name)});$('#publish')?.addEventListener('click',e=>{e.preventDefault();savePost('published')});$('#draft')?.addEventListener('click',e=>{e.preventDefault();savePost('draft')});$('#cancel')?.addEventListener('click',resetPost);$('#newPost')?.addEventListener('click',()=>{resetPost();openWorkspace('posts');window.scrollTo({top:0,behavior:'smooth'})});['#postSearch','#postCategoryFilter','#postStatusFilter'].forEach(s=>$(s)?.addEventListener('input',renderPosts));['#postCategoryFilter','#postStatusFilter'].forEach(s=>$(s)?.addEventListener('change',renderPosts))}
function initEditor(){if(!window.tinymce||tinymce.get('content'))return;tinymce.init({selector:'#content',height:420,plugins:'lists link image media code table',toolbar:'undo redo | blocks | fontfamily fontsize | bold italic underline strikethrough | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media table | removeformat | code',media_live_embeds:true,toolbar_mode:'sliding',branding:false,images_upload_handler:async blobInfo=>{const b=await blobInfo.blob().arrayBuffer();let bin='';new Uint8Array(b).forEach(x=>bin+=String.fromCharCode(x));const d=await api('upload',{method:'POST',body:JSON.stringify({name:blobInfo.filename(),mime:blobInfo.blob().type,data:btoa(bin)})});return d.url}}).catch(e=>console.warn('TinyMCE:',e.message))}

function loginSetup(){const form=$('#loginForm');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('button'),m=$('#loginMsg');try{b.disabled=true;b.textContent='Login हुँदैछ...';const r=await fetch('/.netlify/functions/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#username').value.trim(),password:$('#password').value})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Login failed');localStorage.setItem('nb_admin_token',d.token);localStorage.setItem('nb_admin_username',$('#username').value.trim());location.reload()}catch(e){if(m)m.textContent=e.message;msg(e.message)}finally{b.disabled=false;b.textContent='Login'}})}
function logout(){localStorage.removeItem('nb_admin_token');localStorage.removeItem('nb_admin_username');location.href='/admin'}

function injectStyles(){if($('#nb-admin-nav-style'))return;const s=document.createElement('style');s.id='nb-admin-nav-style';s.textContent=`.nb-admin-nav{position:sticky;top:0;z-index:20;background:#650a03;color:#fff;border-radius:14px;margin:0 0 22px;padding:8px;display:flex;gap:6px;overflow:auto;box-shadow:0 8px 24px rgba(0,0,0,.12)}.nb-admin-nav button{border:0;background:transparent;color:#fff;padding:11px 14px;border-radius:10px;white-space:nowrap;cursor:pointer;font-weight:700}.nb-admin-nav button:hover,.nb-admin-nav button.active{background:#8f0e04}.nb-workspace{display:none}.nb-workspace.active{display:block}.nb-panel{background:#fff;border:1px solid #eadfdc;border-radius:16px;padding:20px;margin-bottom:18px;box-shadow:0 5px 18px rgba(0,0,0,.06)}.nb-panel h2{margin-top:0}.nb-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.nb-kpi{padding:16px;border-radius:14px;background:#fff5f3;border:1px solid #f0d6d2}.nb-kpi b{display:block;font-size:1.5rem;margin-top:5px}.nb-toolbar{display:flex;gap:10px;flex-wrap:wrap}.nb-toolbar input{flex:1;min-width:220px}.nb-table{width:100%;border-collapse:collapse}.nb-table th,.nb-table td{padding:10px;border-bottom:1px solid #eee;text-align:left}.nb-empty{padding:25px;text-align:center;color:#777}@media(max-width:800px){.nb-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.nb-grid{grid-template-columns:1fr}.nb-panel{padding:14px}.nb-admin-nav button{padding:10px 11px}}`;document.head.appendChild(s)}
function workspace(id,title,html=''){let el=document.getElementById(id);if(el)return el;el=document.createElement('section');el.id=id;el.className='nb-workspace';el.innerHTML=`<div class="nb-panel"><h2>${title}</h2>${html}</div>`;$('#dashboard')?.appendChild(el);return el}
function buildNav(){if($('.nb-admin-nav'))return;injectStyles();const nav=document.createElement('nav');nav.className='nb-admin-nav';nav.setAttribute('aria-label','Admin management');[['dashboard','ड्यासबोर्ड'],['posts','पोस्ट व्यवस्थापन'],['analytics','Google Analytics'],['exams','परीक्षा व्यवस्थापन'],['history','परीक्षा इतिहास'],['users','प्रयोगकर्ता व्यवस्थापन'],['account','खाता व्यवस्थापन']].forEach(([id,label])=>{const b=document.createElement('button');b.type='button';b.dataset.workspace=id;b.textContent=label;b.onclick=()=>openWorkspace(id);nav.appendChild(b)});const anchor=$('.dashboard-summary');anchor?.parentNode?.insertBefore(nav,anchor);const dash=workspace('nbWsDashboard','ड्यासबोर्ड');dash.innerHTML='<div class="nb-panel"><h2>ड्यासबोर्ड</h2><div class="nb-grid"><div class="nb-kpi">कुल पोस्ट<b id="nbTotal">0</b></div><div class="nb-kpi">प्रकाशित<b id="nbPublished">0</b></div><div class="nb-kpi">ड्राफ्ट<b id="nbDraft">0</b></div><div class="nb-kpi">श्रेणी<b id="nbCategories">0</b></div></div></div>';workspace('nbWsAnalytics','Google Analytics','<div id="nbAnalyticsBox" class="nb-empty">Analytics data लोड हुँदैछ...</div>');workspace('nbWsExams','परीक्षा व्यवस्थापन','<div id="nbExamBox" class="nb-empty">परीक्षा data लोड हुँदैछ...</div>');workspace('nbWsHistory','परीक्षा इतिहास','<div class="nb-toolbar"><input id="nbHistoryUser" placeholder="Username / User ID खोज्नुहोस्"><button class="btn btn-primary" id="nbHistorySearch">खोज्नुहोस्</button></div><div id="nbHistoryBox" class="nb-empty">पहिले user खोज्नुहोस्।</div>');workspace('nbWsUsers','प्रयोगकर्ता व्यवस्थापन','<div class="nb-toolbar"><button class="btn btn-primary" id="nbLoadUsers">प्रयोगकर्ताहरू लोड गर्नुहोस्</button></div><div id="nbUsersBox" class="nb-empty">बटन थिचेर सूची खोल्नुहोस्।</div>');const oldMain=$('.admin-main');if(oldMain)oldMain.id='nbOldPostWorkspace';const account=$('#accountCard');if(account)account.id='nbOldAccountWorkspace';openWorkspace('dashboard')}
function allWorkspaces(){return ['nbWsDashboard','nbOldPostWorkspace','nbWsAnalytics','nbWsExams','nbWsHistory','nbWsUsers','nbOldAccountWorkspace'].map(id=>document.getElementById(id)).filter(Boolean)}
async function openWorkspace(id){const map={dashboard:'nbWsDashboard',posts:'nbOldPostWorkspace',analytics:'nbWsAnalytics',exams:'nbWsExams',history:'nbWsHistory',users:'nbWsUsers',account:'nbOldAccountWorkspace'};allWorkspaces().forEach(x=>x.classList.remove('active'));const target=document.getElementById(map[id]);if(target)target.classList.add('active');document.querySelectorAll('.nb-admin-nav button').forEach(b=>b.classList.toggle('active',b.dataset.workspace===id));if(id==='analytics')loadAnalytics();if(id==='exams')loadExams();if(id==='users')loadUsers()}
async function loadAnalytics(){const box=$('#nbAnalyticsBox');try{const d=await api('analytics');const x=d.data||d;box.innerHTML=`<div class="nb-grid"><div class="nb-kpi">Users<b>${esc(x.users??x.totalUsers??'—')}</b></div><div class="nb-kpi">Sessions<b>${esc(x.sessions??'—')}</b></div><div class="nb-kpi">Views<b>${esc(x.views??x.screenPageViews??'—')}</b></div><div class="nb-kpi">Active Users<b>${esc(x.activeUsers??'—')}</b></div></div>`}catch(e){box.innerHTML=`<div class="nb-empty">Analytics load हुन सकेन: ${esc(e.message)}</div>`}}
async function examApi(action,options={}){const r=await fetch(`/.netlify/functions/exam-api?action=${encodeURIComponent(action)}`,{...options,headers:{'Content-Type':'application/json','Authorization':`Bearer ${token()}`,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Exam request failed');return d}
async function loadExams(){const box=$('#nbExamBox');try{const d=await examApi('admin-data');const exams=d.data?.exams||d.exams||[];if(!exams.length){box.innerHTML='<div class="nb-empty">अहिले परीक्षा data छैन।</div>';return}box.innerHTML='<div class="nb-grid">'+exams.map(x=>`<div class="nb-kpi"><strong>${esc(x.title||x.name||'परीक्षा')}</strong><small>प्रश्न: ${esc(x.questionCount??x.questions?.length??0)}</small><b>${esc(x.duration??x.durationMinutes??'—')}</b><small>Pass: ${esc(x.passPercentage??x.passPercent??'—')}</small></div>`).join('')+'</div>'}catch(e){box.innerHTML=`<div class="nb-empty">परीक्षा data load हुन सकेन: ${esc(e.message)}</div>`}}
async function loadHistory(){const q=$('#nbHistoryUser')?.value.trim(),box=$('#nbHistoryBox');if(!q){box.textContent='पहिले user खोज्नुहोस्।';return}try{const d=await examApi('history&user='+encodeURIComponent(q));const rows=d.data?.history||d.history||d.data||[];if(!Array.isArray(rows)||!rows.length){box.innerHTML='<div class="nb-empty">यो user को history भेटिएन।</div>';return}box.innerHTML='<table class="nb-table"><thead><tr><th>परीक्षा</th><th>स्कोर</th><th>मिति</th></tr></thead><tbody>'+rows.map(x=>`<tr><td>${esc(x.examTitle||x.exam||x.title||'—')}</td><td>${esc(x.score??x.marks??'—')}</td><td>${esc(x.date||x.createdAt||'—')}</td></tr>`).join('')+'</tbody></table>'}catch(e){box.innerHTML=`<div class="nb-empty">History load हुन सकेन: ${esc(e.message)}</div>`}}
async function loadUsers(){const box=$('#nbUsersBox');try{const d=await examApi('users');const rows=d.data?.users||d.users||d.data||[];if(!Array.isArray(rows)||!rows.length){box.innerHTML='<div class="nb-empty">प्रयोगकर्ता भेटिएन।</div>';return}box.innerHTML='<table class="nb-table"><thead><tr><th>User</th><th>Email</th><th>Action</th></tr></thead><tbody>'+rows.map(x=>{const id=x.id||x.userId||x.username;return`<tr><td>${esc(x.username||x.name||id)}</td><td>${esc(x.email||'—')}</td><td><button class="btn btn-danger" type="button" data-delete-user="${esc(id)}">मेटाउनुहोस्</button></td></tr>`}).join('')+'</tbody></table>';box.querySelectorAll('[data-delete-user]').forEach(b=>b.onclick=async()=>{if(!confirm('यो प्रयोगकर्ता मेटाउने?'))return;try{await examApi('delete-user',{method:'POST',body:JSON.stringify({userId:b.dataset.deleteUser,id:b.dataset.deleteUser})});msg('प्रयोगकर्ता मेटाइयो');loadUsers()}catch(e){msg(e.message)}})}catch(e){box.innerHTML=`<div class="nb-empty">Users load हुन सकेन: ${esc(e.message)}</div>`}}

async function changePassword(event){event.preventDefault();const btn=$('#changePasswordBtn');if(!btn)return;const currentPassword=$('#currentPassword')?.value||'',newPassword=$('#newPassword')?.value||'',confirmPassword=$('#confirmPassword')?.value||'';if(!currentPassword){msg('हालको password राख्नुहोस्');return}if(newPassword.length<10){msg('नयाँ password कम्तीमा 10 characters हुनुपर्छ');return}if(newPassword!==confirmPassword){msg('नयाँ password र confirmation मिलेन');return}try{btn.disabled=true;btn.textContent='परिवर्तन हुँदैछ...';const r=await fetch('/.netlify/functions/change-password',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token()}`},body:JSON.stringify({currentPassword,newPassword,confirmPassword})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Password परिवर्तन हुन सकेन');localStorage.removeItem('nb_admin_token');alert(d.message||'Password परिवर्तन भयो। अब नयाँ password बाट login गर्नुहोस्।');location.reload()}catch(e){msg(e.message)}finally{btn.disabled=false;btn.textContent='Password परिवर्तन गर्नुहोस्'}}

function boot(){if(!token()){$('#login').style.display='';$('#dashboard').style.display='none';loginSetup();return}$('#login').style.display='none';$('#dashboard').style.display='';$('#logout')?.addEventListener('click',logout);$('#accountLogout')?.addEventListener('click',logout);$('#changePasswordForm')?.addEventListener('submit',changePassword);setupPostEditor();buildNav();loadPosts();initEditor();$('#nbHistorySearch')?.addEventListener('click',loadHistory);$('#nbLoadUsers')?.addEventListener('click',loadUsers)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();