/* DI renderer: preserves exact question/options; renders complete shared tables and charts responsively. */
(function(){
const E=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const COL=['#8f0e04','#2563eb','#059669','#d97706','#7c3aed','#db2777'];
function pict(q){const t=[q?.type,q?.category,q?.topic,q?.subject,q?.q,q?.question].filter(Boolean).join(' ').toLowerCase();return /pictorial|non-verbal|figure-count|triangle-count|आकृति|घुमाइ|भुजा क्रम|दर्पण|प्रतिबिम्ब/.test(t)}
function isDI(q){if(!q||pict(q))return false;const t=[q.category,q.subject,q.unit,q.type,q.topic].filter(Boolean).join(' ').toLowerCase();return /data interpretation|data-interpretation|datainterpretation|डेटा व्याख्या/.test(t)||['table','bar-chart','line-graph','pie-chart'].includes(String(q.type||'').toLowerCase())}
function nums(s){return String(s).split(/\s*[,|]\s*/).map(x=>x.trim()).filter(Boolean)}
function parse(q){const type=String(q.type||'table').toLowerCase(),raw=String(q.data||q.figure||'').trim();if(!raw)return null;let title='',body=raw,rows=[];const colon=raw.indexOf(':');if(colon>0){title=raw.slice(0,colon).trim();body=raw.slice(colon+1).trim()}
if(type==='pie-chart'){rows=nums(body).map(x=>{const m=x.match(/^(.+?)\s*(\d+(?:\.\d+)?)%\.?$/);return m?[m[1].trim(),m[2]+'%']:null}).filter(Boolean);return{type,title,rows}}
const parts=body.split(/\s*;\s*/).map(x=>x.trim()).filter(Boolean);
if(type==='bar-chart'){rows=parts.map(p=>{const m=p.match(/^([A-Za-z][A-Za-z0-9_-]*)\s+(.+)$/);return m?[m[1],...nums(m[2])]:nums(p)});return{type,title,rows}}
if(type==='line-graph'){if(parts.length===1){const a=nums(parts[0]);const labels=[],vals=[];a.forEach(x=>{const m=x.match(/^([A-Za-z]+)(-?\d+(?:\.\d+)?)$/);if(m){labels.push(m[1]);vals.push(m[2])}});if(labels.length===a.length)return{type,title,labels,rows:[['Visits',...vals]]}}rows=parts.map(p=>{const m=p.match(/^([^:]+):\s*(.+)$/);return m?[m[1].trim(),...nums(m[2])]:nums(p)});return{type,title,rows}}
rows=parts.map(p=>{let m=p.match(/^(.+?)\s+(\d+(?:\.\d+)?%?)\s*→\s*(\d+(?:\.\d+)?%?)\s*\.?$/);if(m)return[m[1].trim(),m[2],m[3]];m=p.match(/^([A-Za-z][A-Za-z0-9_-]*)\s+(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)(?:\s+(.+))?$/);if(m)return[m[1],m[2],m[3]];m=p.match(/^([A-Za-z][A-Za-z0-9_-]*)(\d+(?:\.\d+)?)\s+at\s*(\d+(?:\.\d+)?)%$/i);if(m)return[m[1],m[2],m[3]+'%'];return nums(p).length>1?nums(p):[p]});return{type,title,rows}}
function box(title,body,kind){return `<section class="exam-stimulus di-core-stimulus ${kind||''}" aria-label="Data Interpretation data"><div class="di-stimulus-head"><span>Data Interpretation</span>${title?`<strong>${E(title)}</strong>`:''}</div>${body}</section>`}
function table(d){if(!d.rows.length)return'';const n=Math.max(...d.rows.map(r=>r.length));let h=['विवरण'];if(n===3&&/\d{4}\s*→\s*\d{4}/.test(d.title)){const y=d.title.match(/\d{4}/g);h=['विवरण',y[0],y[1]]}else if(n===3&&d.rows.every(r=>/%$/.test(String(r[2]||''))))h=['विवरण','कुल','प्रतिशत'];else if(n===3&&d.rows.every(r=>r.length===3))h=['विवरण','मान 1','मान 2'];else for(let i=1;i<n;i++)h.push(`मान ${i}`);const html=`<div class="di-table-scroll"><table class="di-table"><thead><tr>${h.map(x=>`<th>${E(x)}</th>`).join('')}</tr></thead><tbody>${d.rows.map(r=>`<tr>${h.map((_,i)=>`<td>${E(r[i]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;return box(d.title,html,'di-table-box')}
function pie(d){const v=d.rows.map(r=>parseFloat(r[1])||0),sum=v.reduce((a,b)=>a+b,0);if(sum<=0)return'';let a=0;const stops=v.map((x,i)=>{const z=x/sum*360,s=`${COL[i%COL.length]} ${a}deg ${a+z}deg`;a+=z;return s}).join(',');const legend=d.rows.map((r,i)=>`<div class="di-legend-row"><i style="background:${COL[i%COL.length]}"></i><span>${E(r[0])}</span><b>${E(r[1])}</b></div>`).join('');return box(d.title,`<div class="di-pie-layout"><div class="di-pie" style="background:conic-gradient(${stops})"><span>100%</span></div><div class="di-legend">${legend}</div></div>`,'di-pie-box')}
function chart(d,line){let labels=d.labels||[],series=[];if(d.labels)series=[{name:'Visits',vals:d.rows[0].slice(1).map(Number)}];else{series=d.rows.map(r=>({name:r[0],vals:r.slice(1).map(v=>parseFloat(String(v).replace(/,/g,''))||0)}));const count=Math.max(...series.map(s=>s.vals.length));labels=Array.from({length:count},(_,i)=>`मान ${i+1}`)}if(!series.length||!labels.length)return'';const max=Math.max(1,...series.flatMap(s=>s.vals)),w=760,h=360,L=62,R=18,T=30,B=68,PW=w-L-R,PH=h-T-B;let s=`<svg class="di-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${line?'Line graph':'Bar chart'}">`;for(let g=0;g<=5;g++){const y=T+PH-PH*g/5;s+=`<line x1="${L}" y1="${y}" x2="${w-R}" y2="${y}" stroke="#dbe2ea"/><text x="${L-8}" y="${y+4}" text-anchor="end" font-size="12">${Math.round(max*g/5)}</text>`}if(line){labels.forEach((x,i)=>{const px=L+(labels.length===1?PW/2:i*PW/(labels.length-1));s+=`<text x="${px}" y="${h-35}" text-anchor="middle" font-size="12" font-weight="700">${E(x)}</text>`});series.forEach((q,si)=>{const pts=q.vals.map((v,i)=>{const x=L+(labels.length===1?PW/2:i*PW/(labels.length-1)),y=T+PH-PH*v/max;return[x,y,v]});s+=`<polyline fill="none" stroke="${COL[si%COL.length]}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" points="${pts.map(p=>p[0]+','+p[1]).join(' ')}"/>`;pts.forEach(p=>s+=`<circle cx="${p[0]}" cy="${p[1]}" r="6" fill="#fff" stroke="${COL[si%COL.length]}" stroke-width="4"/><text x="${p[0]}" y="${p[1]-11}" text-anchor="middle" font-size="11" font-weight="700">${p[2]}</text>`)})}else{const gw=PW/labels.length,bw=Math.min(30,(gw-14)/series.length);labels.forEach((x,i)=>{const x0=L+i*gw;series.forEach((q,si)=>{const v=q.vals[i]||0,bh=PH*v/max,px=x0+(gw-series.length*bw)/2+si*bw;s+=`<rect x="${px+2}" y="${T+PH-bh}" width="${Math.max(7,bw-4)}" height="${bh}" rx="4" fill="${COL[si%COL.length]}"/><text x="${px+bw/2}" y="${Math.max(18,T+PH-bh-5)}" text-anchor="middle" font-size="11" font-weight="700">${v}</text>`});s+=`<text x="${x0+gw/2}" y="${h-35}" text-anchor="middle" font-size="12" font-weight="700">${E(x)}</text>`})}s+='</svg>';return box(d.title,s,line?'di-line-box':'di-bar-box')}
function render(){const c=document.getElementById('questionCard');if(!c)return;let q;try{q=examQuestions[current]}catch(e){return}c.querySelectorAll('.di-core-stimulus,.data-stimulus').forEach(x=>x.remove());if(!isDI(q))return;const d=parse(q);if(!d)return;let html=d.type==='pie-chart'?pie(d):d.type==='bar-chart'?chart(d,false):d.type==='line-graph'?chart(d,true):table(d);if(html){const h=c.querySelector('h2');if(h)h.insertAdjacentHTML('afterend',html);else c.insertAdjacentHTML('afterbegin',html)}}
function install(){if(typeof window.stimulusHTML==='function'&&!window.__nbStimulusSuppressed){window.__nbOriginalStimulusHTML=window.stimulusHTML;window.stimulusHTML=function(q,show){if(q?.passage)return `<div class="exam-stimulus passage-stimulus">${show?'<div class="stimulus-label">पाठ / Paragraph</div>':''}<div style="line-height:1.75;white-space:pre-line">${E(q.passage)}</div></div>`;return''};window.__nbStimulusSuppressed=true}if(typeof window.renderQuestion==='function'&&!window.__nbRenderWrapped){const o=window.renderQuestion;window.renderQuestion=function(){o();render()};window.__nbRenderWrapped=true;render()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setTimeout(install,0);
})();