const API='/.netlify/functions/exam-api?action=';const $=s=>document.querySelector(s);let data=null,editing=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const token=()=>localStorage.getItem('nb_admin_token');const toast=m=>{const t=$('#toast');t.textContent=m;t.className='show';setTimeout(()=>t.className='',2500)};
async function api(action,opt={}){const r=await fetch(API+action,{...opt,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token(),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
async function init(){if(!token()){location.href='admin.html';return}try{data=(await api('admin-data')).data;render()}catch(e){alert(e.message);location.href='admin.html'}}
function render(){renderExams();renderQuestions()}
function renderExams(){$('#exams').innerHTML=data.exams.map((e,i)=>`<div class="exam-row"><div><b>${esc(e.title)}</b><small>${esc(e.description||'')}</small></div><label>प्रश्न <input type="number" min="1" value="${e.questionCount}" data-ex="${i}" data-k="questionCount"></label><label>मिनेट <input type="number" min="1" value="${e.durationMinutes}" data-ex="${i}" data-k="durationMinutes"></label><label>सही + <input type="number" step="0.1" value="${e.positiveMark}" data-ex="${i}" data-k="positiveMark"></label><label>गलत − <input type="number" step="0.1" value="${e.negativeMark}" data-ex="${i}" data-k="negativeMark"></label><label>पास % <input type="number" value="${e.passPercent}" data-ex="${i}" data-k="passPercent"></label><label><input type="checkbox" ${e.enabled!==false?'checked':''} data-ex="${i}" data-k="enabled"> सक्रिय</label></div>`).join('');document.querySelectorAll('[data-ex]').forEach(x=>x.onchange=()=>{const e=data.exams[Number(x.dataset.ex)],k=x.dataset.k;e[k]=x.type==='checkbox'?x.checked:Number(x.value)})}
function renderQuestions(){const search=$('#search').value.trim().toLowerCase(),ef=$('#filterExam').value,tf=$('#filterType').value;$('#filterExam').innerHTML='<option value="">सबै परीक्षा</option>'+data.exams.map(e=>`<option value="${esc(e.id)}">${esc(e.title)}</option>`).join('');$('#filterExam').value=ef;const qs=data.questions.filter(q=>(!search||`${q.q} ${q.subject} ${q.topic}`.toLowerCase().includes(search))&&(!ef||q.examIds.includes(ef))&&(!tf||q.type===tf));$('#questions').innerHTML=qs.map(q=>`<article class="qrow"><div><b>${esc(q.q)}</b><small>${esc(q.subject)} · ${esc(q.topic)} · ${q.type.toUpperCase()}</small><p>सही उत्तर: ${esc(q.options[q.correct])}</p></div><div class="qactions"><button class="btn btn-outline" onclick="editQ('${q.id}')">सम्पादन</button><button class="btn" onclick="deleteQ('${q.id}')">मेटाउनुहोस्</button></div></article>`).join('')||'<p>प्रश्न भेटिएन।</p>'}
function form(q={id:'',examIds:[data.exams[0]?.id],subject:'सामान्य ज्ञान',topic:'',type:'gk',q:'',options:['','','',''],correct:0,explanation:'',solution:''}){$('#questionForm').hidden=false;editing=q.id||null;$('#questionForm').innerHTML=`<div class="qform"><h3>${q.id?'प्रश्न सम्पादन':'नयाँ प्रश्न'}</h3><label>परीक्षा<select id="fEx" multiple>${data.exams.map(e=>`<option value="${esc(e.id)}" ${q.examIds.includes(e.id)?'selected':''}>${esc(e.title)}</option>`).join('')}</select></label><div class="two"><label>विषय<input id="fSub" value="${esc(q.subject)}"></label><label>Topic / पाठ्यक्रम इकाइ<input id="fTopic" value="${esc(q.topic)}"></label></div><label>प्रकार<select id="fType"><option value="gk" ${q.type==='gk'?'selected':''}>GK/विषयगत</option><option value="iq" ${q.type==='iq'?'selected':''}>IQ</option></select></label><label>प्रश्न<textarea id="fQ">${esc(q.q)}</textarea></label>${q.options.map((o,i)=>`<label>विकल्प ${String.fromCharCode(65+i)}<input id="fo${i}" value="${esc(o)}"></label>`).join('')}<label>सही विकल्प<select id="fCorrect">${q.options.map((o,i)=>`<option value="${i}" ${q.correct===i?'selected':''}>${String.fromCharCode(65+i)}</option>`).join('')}</select></label><label>व्याख्या<textarea id="fExp">${esc(q.explanation)}</textarea></label><label>IQ Solution<textarea id="fSol">${esc(q.solution)}</textarea></label><div><button class="btn btn-primary" id="saveQ">प्रश्न सुरक्षित गर्नुहोस्</button> <button class="btn" id="cancelQ">रद्द</button></div></div>`;$('#saveQ').onclick=saveQ;$('#cancelQ').onclick=()=>{$('#questionForm').hidden=true}}
function editQ(id){const q=data.questions.find(x=>x.id===id);if(q)form(q)}
function deleteQ(id){if(!confirm('यो प्रश्न मेटाउने?'))return;data.questions=data.questions.filter(q=>q.id!==id);renderQuestions();toast('प्रश्न हटाइयो; अन्त्यमा Save गर्नुहोस्।')}
function saveQ(){const q={id:editing||`q-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,examIds:[...$('#fEx').selectedOptions].map(x=>x.value),subject:$('#fSub').value.trim(),topic:$('#fTopic').value.trim(),type:$('#fType').value,q:$('#fQ').value.trim(),options:[0,1,2,3].map(i=>$(`#fo${i}`).value.trim()),correct:Number($('#fCorrect').value),explanation:$('#fExp').value.trim(),solution:$('#fSol').value.trim()};if(!q.examIds.length||!q.q||q.options.some(x=>!x)){alert('परीक्षा, प्रश्न र चारवटै विकल्प आवश्यक छन्।');return}const i=data.questions.findIndex(x=>x.id===q.id);if(i>=0)data.questions[i]=q;else data.questions.unshift(q);$('#questionForm').hidden=true;renderQuestions();toast('प्रश्न तयार भयो; अन्त्यमा Save गर्नुहोस्।')}
$('#newQ').onclick=()=>form();$('#save').onclick=async()=>{try{$('#save').disabled=true;await api('save-data',{method:'POST',body:JSON.stringify({data})});toast('सबै Exam/Question Bank GitHub मा सुरक्षित भयो।')}catch(e){alert(e.message)}finally{$('#save').disabled=false}};$('#search').oninput=renderQuestions;$('#filterExam').onchange=renderQuestions;$('#filterType').onchange=renderQuestions;init();