/* FINAL DI GUARD v3
   Always uses the ACTUAL question object currently displayed by exam.js.
   Never matches a question to another bank question by text.
*/
(function(){
  const card=()=>document.getElementById('questionCard');
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const actual=()=>{try{const a=window.examQuestions;if(!Array.isArray(a))return null;const bs=[...document.querySelectorAll('#questionNav button')];let i=bs.findIndex(b=>b.classList.contains('active'));if(i<0){const h=card()?.querySelector('h2');const m=String(h?.textContent||'').match(/^\s*(\d+)\s*[.)]/);i=m?Number(m[1])-1:0}return a[i]||null}catch(e){return null}};
  const pict=q=>{if(!q)return false;const t=String([q.type,q.topic,q.subject,q.category,q.unit,q.q,q.question].filter(Boolean).join(' ')).toLowerCase();return /pictorial|non-verbal|figure-count|triangle-count|triangle-counting|आकृति क्रम|रेखा क्रम|घुमाइ|भुजा क्रम|भर्ने क्रम|भराइ|दर्पण प्रतिबिम्ब|प्रतिबिम्ब/.test(t)};
  const di=q=>{if(!q||pict(q))return false;const t=String([q.category,q.type,q.topic,q.subject,q.unit].filter(Boolean).join(' ')).toLowerCase();return /data interpretation|data-interpretation|datainterpretation|डेटा व्याख्या/.test(t)||['pie-chart','bar-chart','line-graph'].includes(String(q.type||'').toLowerCase())||!!q.dataInterpretation};
  function remove(){const c=card();if(c)c.querySelectorAll('.data-stimulus,.live-di-stimulus').forEach(x=>x.remove())}
  function parse(q){const raw=String(q?.data||q?.figure||'').trim();if(!raw)return null;const type=String(q.type||'table').toLowerCase();let title='',body=raw,rows=[];const c=raw.indexOf(':');if(c>0){title=raw.slice(0,c).trim();body=raw.slice(c+1).trim()}
    const parts=body.split(/\s*;\s*/).map(x=>x.trim().replace(/[.]$/,'')).filter(Boolean);
    if(type==='pie-chart'){parts.forEach(x=>{const m=x.match(/^(.+?)\s*(\d+(?:\.\d+)?)%$/);if(m)rows.push([m[1].trim(),m[2]+'%'])})}
    else parts.forEach(x=>{const m=x.match(/^([A-Za-z][A-Za-z0-9_-]*)\s+(.+)$/);if(m)rows.push([m[1],...m[2].split(/\s*[,|]\s*/).filter(Boolean)]);else rows.push(x.split(/\s*[,|]\s*/).filter(Boolean))});
    return{title,type,rows}
  }
  function box(title,html){return `<div class="exam-stimulus live-di-stimulus data-stimulus" style="margin:14px 0;padding:14px;border:1px solid #d7dee8;border-radius:14px;background:#fff;box-shadow:0 6px 18px rgba(15,23,42,.06)">${title?`<div style="font-weight:850;color:#8f0e04;margin-bottom:12px">${esc(title)}</div>`:''}${html}</div>`}
  function table(d){const n=Math.max(1,...d.rows.map(r=>r.length));const h=Array.from({length:n},(_,i)=>i?'मान '+i:'विवरण');return box(d.title,`<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr>${h.map((x,i)=>`<th style="padding:11px 8px;background:${i?'#8f0e04':'#650a03'};color:#fff">${esc(x)}</th>`).join('')}</tr></thead><tbody>${d.rows.map((r,j)=>`<tr>${h.map((_,i)=>`<td style="padding:10px 8px;border-bottom:1px solid #eee;text-align:${i?'center':'left'};background:${j%2?'#fff':'#fff8f6'}">${esc(r[i]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`)}
  function pie(d){const p=['#ef4444','#f59e0b','#10b981','#3b82f6','#8b5cf6','#ec4899','#14b8a6','#f97316'];let a=0;const stops=d.rows.map((r,i)=>{const v=parseFloat(r[1])||0;const z=`${p[i%p.length]} ${a}deg ${a+v/100*360}deg`;a+=v/100*360;return z}).join(',');return box(d.title,`<div style="display:grid;grid-template-columns:minmax(160px,260px) 1fr;gap:20px;align-items:center"><div style="width:min(260px,70vw);aspect-ratio:1;border-radius:50%;background:conic-gradient(${stops});box-shadow:inset 0 0 0 18px #fff,0 8px 22px rgba(0,0,0,.12);margin:auto"></div><div>${d.rows.map((r,i)=>`<div style="display:flex;gap:8px;align-items:center;margin:7px 0"><span style="width:13px;height:13px;border-radius:4px;background:${p[i%p.length]};display:inline-block"></span><span>${esc(r[0])}</span><b style="margin-left:auto">${esc(r[1])}</b></div>`).join('')}</div></div>`)}
  function render(){const c=card();if(!c)return;const q=actual();if(!q||!di(q)){remove();return}if(c.querySelector('.data-stimulus'))return;const d=parse(q);if(!d||!d.rows.length)return;const h=c.querySelector('h2');if(!h)return;h.insertAdjacentHTML('beforebegin',d.type==='pie-chart'?pie(d):table(d))}
  function boot(){const c=card();if(!c)return;new MutationObserver(()=>setTimeout(render,20)).observe(c,{childList:true,subtree:true});render();[100,300,700,1500].forEach(x=>setTimeout(render,x))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();