/* DI guard + live renderer
   IMPORTANT: normal quantitative/verbal/non-verbal questions must never be rendered as DI.
*/
(function(){
  const card=()=>document.getElementById('questionCard');
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const key=s=>String(s??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'');
  function live(){try{return typeof examQuestions!=='undefined'&&Array.isArray(examQuestions)?examQuestions:[]}catch(e){return[]}}
  function current(){const h=card()?.querySelector('h2');if(!h)return null;const t=String(h.textContent||'').replace(/^\s*\d+\s*[.)]\s*/,'');const k=key(t);return live().find(q=>key(q.q||q.question)===k)||live().find(q=>{const z=key(q.q||q.question);return z&&((z.length>20&&k.includes(z))||(k.length>20&&z.includes(k)))})||null}
  function pict(q){const t=String([q?.type,q?.topic,q?.category,q?.subject,q?.q,q?.question].filter(Boolean).join(' ')).toLowerCase();return /pictorial|non-verbal|figure-count|triangle-count|आकृति क्रम|रेखा क्रम|घुमाइ|भुजा क्रम|भर्ने क्रम|दर्पण प्रतिबिम्ब|प्रतिबिम्ब/.test(t)}
  function isDI(q){if(!q||pict(q))return false;const t=String([q.type,q.category,q.topic,q.subject,q.unit].filter(Boolean).join(' ')).toLowerCase();if(/data interpretation|data-interpretation|datainterpretation|डेटा व्याख्या/.test(t))return true;const type=String(q.type||'').toLowerCase();if(['pie-chart','bar-chart','line-graph'].includes(type))return true;return !!(q.diData||q.diChart||q.diImage||q.dataInterpretation)}
  function removeStimuli(){const c=card();if(!c)return;c.querySelectorAll('.data-stimulus,.live-di-stimulus').forEach(e=>e.remove())}
  function box(body){return `<div class="exam-stimulus live-di-stimulus data-stimulus" style="margin:14px 0;padding:14px;border:1px solid #d7dee8;border-radius:14px;background:#fff;box-shadow:0 6px 18px rgba(15,23,42,.06)">${body}</div>`}
  function pie(raw){const c=raw.indexOf(':');const title=c>0?raw.slice(0,c).trim():'';const body=c>0?raw.slice(c+1):raw;const rows=[];const re=/([A-Za-z][A-Za-z0-9 +&/-]*?)\s*(\d+(?:\.\d+)?)%/g;let m;while((m=re.exec(body)))rows.push([m[1].trim(),m[2]+'%']);if(rows.length<2)return'';const p=['#ef4444','#f59e0b','#10b981','#3b82f6','#8b5cf6','#ec4899','#14b8a6','#f97316'];let a=0;const stops=rows.map((r,i)=>{const v=Number(r[1].replace('%',''))/100*360;const z=`${p[i%p.length]} ${a}deg ${a+v}deg`;a+=v;return z}).join(',');const legend=rows.map((r,i)=>`<div style="display:flex;align-items:center;gap:8px;margin:7px 0"><span style="width:13px;height:13px;border-radius:4px;background:${p[i%p.length]};display:inline-block"></span><span style="font-weight:650">${esc(r[0])}</span><b style="margin-left:auto">${esc(r[1])}</b></div>`).join('');return box(`${title?`<div style="font-weight:850;color:#8f0e04;margin-bottom:12px">${esc(title)}</div>`:''}<div style="display:grid;grid-template-columns:minmax(180px,260px) 1fr;gap:22px;align-items:center;max-width:720px;margin:auto"><div style="width:min(260px,70vw);aspect-ratio:1;border-radius:50%;background:conic-gradient(${stops});box-shadow:inset 0 0 0 18px #fff,0 8px 22px rgba(0,0,0,.12);margin:auto"></div><div>${legend}</div></div>`)}
  function table(raw){const c=raw.indexOf(':');const title=c>0?raw.slice(0,c).trim():'';const body=c>0?raw.slice(c+1):raw;const rows=body.split(';').map(x=>x.trim()).filter(Boolean);const parsed=rows.map(r=>{const m=r.match(/^([A-Za-z][A-Za-z0-9_-]*)\s+(.+)$/);return m?[m[1],...m[2].split(/\s*[,|]\s*/).filter(Boolean)]:r.split(/\s*[,|]\s*/).filter(Boolean)});if(!parsed.length)return'';const n=Math.max(...parsed.map(r=>r.length));const h=Array.from({length:n},(_,i)=>i?'मान '+i:'विवरण');const html=`${title?`<div style="font-weight:850;color:#8f0e04;margin-bottom:12px">${esc(title)}</div>`:''}<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;background:#fff"><thead><tr>${h.map((x,i)=>`<th style="padding:10px 8px;background:${i?'#8f0e04':'#650a03'};color:#fff;text-align:center;white-space:nowrap">${esc(x)}</th>`).join('')}</tr></thead><tbody>${parsed.map((r,ri)=>`<tr>${h.map((_,i)=>`<td style="padding:9px 8px;border-bottom:1px solid #edf0f4;text-align:${i?'center':'left'};background:${ri%2?'#fff':'#fff8f6'}">${esc(r[i]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;return box(html)}
  function render(){const c=card();if(!c)return;const q=current();if(!isDI(q)){removeStimuli();return}c.querySelectorAll('.data-stimulus,.live-di-stimulus').forEach(e=>e.remove());const raw=String(q.data||q.figure||'').trim();if(!raw)return;const type=String(q.type||'table').toLowerCase();const html=type==='pie-chart'?pie(raw):table(raw);if(!html)return;const h=c.querySelector('h2');if(h)h.insertAdjacentHTML('beforebegin',html)}
  function boot(){const c=card();if(!c)return;new MutationObserver(()=>{clearTimeout(boot.t);boot.t=setTimeout(render,20)}).observe(c,{childList:true,subtree:true});render();[100,300,700,1500].forEach(x=>setTimeout(render,x))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();