/* Single DI renderer: runs synchronously after exam.js renders a question.
   It suppresses exam.js's generic data renderer and renders only the current
   question's own DI stimulus, preventing cross-question leakage and blinking. */
(function(){
  function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]) )}
  function isPict(q){const t=String([q?.type,q?.category,q?.topic,q?.subject,q?.q,q?.question].filter(Boolean).join(' ')).toLowerCase();return /pictorial|non-verbal|figure-count|triangle-count|आकृति क्रम|रेखा क्रम|घुमाइ|भुजा क्रम|भर्ने क्रम|दर्पण प्रतिबिम्ब|प्रतिबिम्ब/.test(t)}
  function isDI(q){if(!q||isPict(q))return false;const t=String([q.category,q.subject,q.unit,q.type,q.topic].filter(Boolean).join(' ')).toLowerCase();return /data interpretation|data-interpretation|datainterpretation|डेटा व्याख्या/.test(t)||['pie-chart','bar-chart','line-graph','table'].includes(String(q.type||'').toLowerCase())}
  function rawData(q){return String(q?.data||q?.figure||'').trim()}
  function parse(q){const raw=rawData(q);if(!raw)return null;const type=String(q.type||'table').toLowerCase();const semi=raw.split(/\s*;\s*/).map(x=>x.trim()).filter(Boolean);let title='';let rows=[];
    if(type==='pie-chart'){
      const c=semi[0].indexOf(':');let body=semi[0];if(c>0){title=semi[0].slice(0,c).trim();body=semi[0].slice(c+1).trim()}
      const tokens=body.split(/\s*,\s*/).map(x=>x.trim()).filter(Boolean);tokens.forEach(x=>{const m=x.match(/^(.+?)\s*(\d+(?:\.\d+)?)%\.?$/);if(m)rows.push([m[1].trim(),m[2]+'%'])});
      return {type,title,rows}
    }
    if(type==='bar-chart'){
      semi.forEach((p,i)=>{const c=p.indexOf(':');let body=p;if(c>0){if(i===0)title=p.slice(0,c).trim();body=p.slice(c+1).trim()}const m=body.match(/^([A-Za-z][A-Za-z0-9_-]*)\s+(.+)$/);rows.push(m?[m[1],...m[2].split(/\s*[,|]\s*/).filter(Boolean)]:body.split(/\s*[,|]\s*/).filter(Boolean))});return{type,title,rows}
    }
    if(type==='line-graph'){
      semi.forEach((p,i)=>{const c=p.indexOf(':');if(c>0){const label=p.slice(0,c).trim(),vals=p.slice(c+1).trim().split(/\s*[,|]\s*/).filter(Boolean);if(i===0)title=label;rows.push([label,...vals])}});return{type,title,rows}
    }
    semi.forEach((p,i)=>{const c=p.indexOf(':');let body=p;if(c>0){if(i===0)title=p.slice(0,c).trim();body=p.slice(c+1).trim()}const m=body.match(/^(.+?)\s+(\d+(?:\.\d+)?%?)\s*→\s*(\d+(?:\.\d+)?%?)\s*\.?$/);if(m)rows.push([m[1].trim(),m[2],m[3]]);else{const m2=body.match(/^([A-Za-z][A-Za-z0-9_-]*)\s+(.+)$/);rows.push(m2?[m2[1],...m2[2].split(/\s*[,|]\s*/).filter(Boolean)]:body.split(/\s*[,|]\s*/).filter(Boolean))}});return{type,title,rows}
  }
  function box(body,title){return `<div class="exam-stimulus di-core-stimulus" style="margin:14px 0;padding:14px;border:1px solid #d7dee8;border-radius:14px;background:#fff;box-shadow:0 6px 18px rgba(15,23,42,.06)">${title?`<div class="stimulus-label" style="font-weight:850;color:#8f0e04;margin-bottom:12px">${esc(title)}</div>`:''}${body}</div>`}
  function pie(d){const rows=d.rows;if(rows.length<2)return'';const colors=['#ef4444','#f59e0b','#10b981','#3b82f6','#8b5cf6','#ec4899','#14b8a6','#f97316'];let a=0;const stops=rows.map((r,i)=>{const v=Number(r[1].replace('%',''))/rows.reduce((s,x)=>s+Number(x[1].replace('%','')),0)*360;const z=`${colors[i%colors.length]} ${a}deg ${a+v}deg`;a+=v;return z}).join(',');const legend=rows.map((r,i)=>`<div style="display:flex;align-items:center;gap:8px;margin:6px 0"><span style="width:13px;height:13px;border-radius:4px;background:${colors[i%colors.length]};display:inline-block;flex:0 0 13px"></span><span style="font-weight:650">${esc(r[0])}</span><b style="margin-left:auto">${esc(r[1])}</b></div>`).join('');return box(`<div style="display:grid;grid-template-columns:minmax(170px,260px) 1fr;gap:22px;align-items:center;max-width:720px;margin:auto"><div style="width:min(260px,70vw);aspect-ratio:1;border-radius:50%;background:conic-gradient(${stops});box-shadow:inset 0 0 0 18px #fff,0 8px 22px rgba(0,0,0,.12);margin:auto"></div><div>${legend}</div></div>`,d.title)}
  function table(d){if(!d.rows.length)return'';const n=Math.max(...d.rows.map(r=>r.length));const heads=Array.from({length:n},(_,i)=>i?'मान '+i:'विवरण');return box(`<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr>${heads.map((h,i)=>`<th style="padding:10px;background:${i?'#8f0e04':'#650a03'};color:#fff">${esc(h)}</th>`).join('')}</tr></thead><tbody>${d.rows.map((r,ri)=>`<tr>${heads.map((_,i)=>`<td style="padding:9px 8px;border-bottom:1px solid #edf0f4;text-align:${i?'center':'left'};background:${ri%2?'#fff':'#fff8f6'}">${esc(r[i]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`,d.title)}
  function line(d){if(d.rows.length<2)return table(d);const labels=d.rows[0].slice(1),series=d.rows.slice(1),w=720,h=330,left=58,right=20,top=28,bottom=62,pw=w-left-right,ph=h-top-bottom,max=Math.max(1,...series.flatMap(r=>r.slice(1).map(v=>Number(String(v).replace(/,/g,''))||0)));let svg=`<svg viewBox="0 0 ${w} ${h}" style="width:100%;height:auto;display:block"><line x1="${left}" y1="${top}" x2="${left}" y2="${h-bottom}" stroke="#94a3b8"/><line x1="${left}" y1="${h-bottom}" x2="${w-right}" y2="${h-bottom}" stroke="#94a3b8"/>`;labels.forEach((x,i)=>{const px=left+(labels.length===1?pw/2:i*pw/(labels.length-1));svg+=`<text x="${px}" y="${h-34}" text-anchor="middle" font-size="12">${esc(x)}</text>`});series.forEach((r,si)=>{const vals=r.slice(1).map(v=>Number(String(v).replace(/,/g,''))||0),pts=vals.map((v,i)=>{const x=left+(labels.length===1?pw/2:i*pw/(labels.length-1)),y=top+ph-ph*v/max;return[x,y,v]});const col=['#ef4444','#3b82f6','#10b981'][si%3];svg+=`<polyline fill="none" stroke="${col}" stroke-width="4" points="${pts.map(p=>p[0]+','+p[1]).join(' ')}"/>`;pts.forEach(p=>svg+=`<circle cx="${p[0]}" cy="${p[1]}" r="5" fill="#fff" stroke="${col}" stroke-width="3"/><text x="${p[0]}" y="${p[1]-9}" text-anchor="middle" font-size="11">${p[2]}</text>`)});svg+='</svg>';return box(svg,d.title)}
  function render(){const c=document.getElementById('questionCard');if(!c)return;const q=window.examQuestions?.[window.current];c.querySelectorAll('.di-core-stimulus,.data-stimulus').forEach(e=>e.remove());if(!isDI(q))return;const d=parse(q);if(!d)return;const html=d.type==='pie-chart'?pie(d):d.type==='line-graph'?line(d):table(d);if(html)c.querySelector('h2')?.insertAdjacentHTML('beforebegin',html)}
  function install(){
    if(typeof window.stimulusHTML==='function'&&!window.__nbStimulusSuppressed){window.__nbOriginalStimulusHTML=window.stimulusHTML;window.stimulusHTML=function(q,showTitle){if(q?.passage){return `<div class="exam-stimulus passage-stimulus">${showTitle?'<div class="stimulus-label">पाठ / Paragraph</div>':''}<div style="line-height:1.75;white-space:pre-line">${esc(q.passage)}</div></div>`}return''};window.__nbStimulusSuppressed=true}
    if(typeof window.renderQuestion==='function'&&!window.__nbRenderWrapped){const orig=window.renderQuestion;window.renderQuestion=function(){orig();render()};window.__nbRenderWrapped=true;render()}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setTimeout(install,0);
})();