/* Runtime DI renderer v3: complete tables/charts for all 2.5 formats and shared stimuli. */
(function(){
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const card=()=>document.getElementById('questionCard');
  const norm=s=>String(s??'').replace(/\s+/g,' ').trim();
  let bank=[],lastObj=null,lastStimulusHTML='';
  async function loadBank(){try{const r=await fetch('exam-data.json?di_runtime='+Date.now(),{cache:'no-store'});const d=await r.json();bank=Array.isArray(d.questions)?d.questions:[]}catch(e){bank=[]}}
  function findQuestion(text){const t=norm(text);return bank.find(q=>norm(q.q||q.question)===t)||null}
  function numericPairs(s){return [...String(s).matchAll(/([A-Za-z]{2,12})\s*(-?\d+(?:\.\d+)?%?)/g)].map(m=>[m[1],m[2]])}
  function dataRows(q){
    const raw=String(q?.data||q?.figure||'').trim();if(!raw)return null;
    const type=String(q.type||'').toLowerCase();let title='',body=raw,parsed=[];
    const c=raw.indexOf(':');if(c>0){title=raw.slice(0,c).trim();body=raw.slice(c+1).trim()}
    const rows=body.split(/\s*;\s*/).map(x=>x.trim().replace(/[.]$/,'')).filter(Boolean);
    if(type==='line-graph'){
      if(rows.length===1){const pairs=numericPairs(rows[0]);if(pairs.length>=2){parsed=[['समय',...pairs.map(x=>x[0])],[title||'मान',...pairs.map(x=>x[1])]]}}
      if(!parsed.length)rows.forEach((row,i)=>{const x=row.indexOf(':');if(x>0){const label=row.slice(0,x).trim();const vals=row.slice(x+1).trim().split(/\s*[,|]\s*/).filter(Boolean);if(i===0&&!title)title=label;parsed.push([label,...vals])}else{const pairs=numericPairs(row);if(pairs.length>=2)parsed.push([title||'मान',...pairs.map(x=>x[1])]);else parsed.push(row.split(/\s*[,|]\s*/).filter(Boolean))}})
    } else if(type==='bar-chart'){
      rows.forEach(row=>{
        let label='',rest=row;const x=row.indexOf(':');if(x>0){if(!title)title=row.slice(0,x).trim();rest=row.slice(x+1).trim()}
        const groups=rest.split(/\s*,\s*/).filter(Boolean);groups.forEach(g=>{const m=g.match(/^([A-Za-z][A-Za-z0-9_-]*)\s+(.+)$/);if(m){const vals=m[2].split(/\s*[,|]\s*/).filter(Boolean);parsed.push([m[1],...vals])}})
        if(!parsed.length&&label)parsed.push([label,rest]);
      });
      if(!parsed.length){rows.forEach(r=>parsed.push(r.split(/\s*[,|]\s*/).filter(Boolean)))}
    } else {
      rows.forEach(row=>{
        const a=row.match(/^(.+?)\s+(\d+(?:\.\d+)?%?)\s*→\s*(\d+(?:\.\d+)?%?)$/);if(a){parsed.push([a[1].trim(),a[2],a[3]]);return}
        const first=row.match(/^([A-Za-z][A-Za-z0-9_-]*)\s+(.+)$/);if(first){const pairs=numericPairs(first[2]);if(pairs.length>=2){parsed.push([first[1],...pairs.map(x=>x[1])]);return}parsed.push([first[1],...first[2].split(/\s*[,|]\s*/).filter(Boolean)]);return}
        parsed.push(row.split(/\s*[,|]\s*/).filter(Boolean));
      });
    }
    let headers=null;
    if(type==='table'&&parsed.length&&parsed.every(r=>r.length===3)){const years=String(title).match(/(\d{4})\s*→\s*(\d{4})/);headers=['विवरण',years?years[1]:'मान १',years?years[2]:'मान २']}
    else if(type==='table'&&parsed.length){
      const firstPairs=numericPairs(rows[0]);if(firstPairs.length>=2)headers=['विवरण',...firstPairs.map(x=>x[0])];
      if(!headers){const max=Math.max(1,...parsed.map(r=>r.length));headers=Array.from({length:max},(_,i)=>i?'मान '+i:'विवरण')}
    }
    return{title,type,parsed,headers};
  }
  function box(title,body){return `<div class="exam-stimulus data-stimulus" style="margin:14px 0;padding:14px;border:1px solid #d7dee8;border-radius:14px;background:linear-gradient(145deg,#fff,#f7f9fc);box-shadow:0 6px 18px rgba(15,23,42,.06)">${title?`<div class="stimulus-label" style="font-weight:850;margin-bottom:12px;color:#8f0e04">${esc(title)}</div>`:''}${body}</div>`}
  function table(d){const h=d.headers||Array.from({length:Math.max(1,...d.parsed.map(r=>r.length))},(_,i)=>i?'मान '+i:'विवरण');const t=`<div style="overflow-x:auto;width:100%;-webkit-overflow-scrolling:touch"><table style="width:100%;min-width:100%;table-layout:auto;border-collapse:separate;border-spacing:0;background:#fff;border:1px solid #d7dee8;border-radius:10px;overflow:hidden"><thead><tr>${h.map((x,i)=>`<th style="padding:11px 8px;background:${i?'#8f0e04':'#650a03'};color:#fff;text-align:center;font-weight:800;white-space:nowrap">${esc(x)}</th>`).join('')}</tr></thead><tbody>${d.parsed.map((r,ri)=>`<tr>${h.map((_,i)=>`<td style="padding:10px 8px;border-bottom:1px solid #edf0f4;text-align:${i?'center':'left'};font-weight:${i?'700':'650'};background:${ri%2?'#fff':'#fff8f6'};white-space:nowrap">${esc(r[i]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;return box(d.title,t)}
  function pie(d){const rows=d.parsed.filter(r=>r.length>=2),sum=rows.reduce((a,r)=>a+(parseFloat(String(r[1]).replace('%',''))||0),0);if(!sum)return'';const p=['#ef4444','#f59e0b','#10b981','#3b82f6','#8b5cf6','#ec4899','#14b8a6','#f97316'];let a=0;const stops=rows.map((r,i)=>{const v=(parseFloat(String(r[1]).replace('%',''))||0)/sum*360,z=`${p[i%p.length]} ${a}deg ${a+v}deg`;a+=v;return z}).join(',');const legend=rows.map((r,i)=>`<div style="display:flex;gap:8px;align-items:center;margin:6px 0"><span style="width:13px;height:13px;border-radius:4px;background:${p[i%p.length]};display:inline-block"></span><span>${esc(r[0])}</span><b style="margin-left:auto">${esc(r[1])}</b></div>`).join('');return box(d.title,`<div style="display:grid;grid-template-columns:minmax(160px,260px) 1fr;gap:20px;align-items:center"><div style="width:min(260px,70vw);aspect-ratio:1;border-radius:50%;background:conic-gradient(${stops});box-shadow:inset 0 0 0 18px #fff,0 8px 22px rgba(0,0,0,.12);margin:auto"></div><div>${legend}</div></div>`)}
  function bars(d){const rows=d.parsed.filter(r=>r.length>=2),vals=rows.map(r=>r.slice(1).map(v=>parseFloat(String(v).replace(/,/g,'').replace('%',''))||0)),series=Math.max(1,...vals.map(x=>x.length)),max=Math.max(1,...vals.flat()),w=760,h=360,l=60,b=72,top=28,ph=h-top-b,gw=(w-l-20)/Math.max(1,rows.length),bw=Math.min(34,(gw-18)/series),p=['#ef4444','#3b82f6','#10b981','#f59e0b','#8b5cf6'];let s=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Bar Chart" style="width:100%;height:auto;display:block"><line x1="${l}" y1="${top}" x2="${l}" y2="${h-b}" stroke="#94a3b8"/><line x1="${l}" y1="${h-b}" x2="${w-10}" y2="${h-b}" stroke="#94a3b8"/>`;for(let g=0;g<=4;g++){const y=top+ph-ph*g/4;s+=`<line x1="${l}" y1="${y}" x2="${w-10}" y2="${y}" stroke="#e2e8f0"/><text x="${l-8}" y="${y+4}" text-anchor="end" font-size="12" fill="#64748b">${Math.round(max*g/4)}</text>`}rows.forEach((r,i)=>{const st=l+i*gw+(gw-vals[i].length*bw)/2;vals[i].forEach((v,j)=>{const bh=ph*v/max,x=st+j*bw,y=top+ph-bh;s+=`<rect x="${x+2}" y="${y}" width="${Math.max(8,bw-5)}" height="${bh}" rx="5" fill="${p[j%p.length]}"/><text x="${x+bw/2}" y="${Math.max(18,y-5)}" text-anchor="middle" font-size="11" font-weight="700" fill="#334155">${v}</text>`});s+=`<text x="${l+i*gw+gw/2}" y="${h-36}" text-anchor="middle" font-size="13" font-weight="700" fill="#334155">${esc(r[0])}</text>`});return box(d.title,s+'</svg>')}
  function lines(d){if(d.parsed.length<2)return'';const labels=d.parsed[0].slice(1),series=d.parsed.slice(1).map(r=>({v:r.slice(1).map(x=>parseFloat(String(x).replace(/,/g,'').replace('%',''))||0)})),max=Math.max(1,...series.flatMap(x=>x.v)),w=760,h=360,l=60,r=20,top=28,b=72,pw=w-l-r,ph=h-top-b,p=['#ef4444','#3b82f6','#10b981','#f59e0b','#8b5cf6'];let s=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Line Graph" style="width:100%;height:auto;display:block"><line x1="${l}" y1="${top}" x2="${l}" y2="${h-b}" stroke="#94a3b8"/><line x1="${l}" y1="${h-b}" x2="${w-r}" y2="${h-b}" stroke="#94a3b8"/>`;for(let g=0;g<=4;g++){const y=top+ph-ph*g/4;s+=`<line x1="${l}" y1="${y}" x2="${w-r}" y2="${y}" stroke="#e2e8f0"/><text x="${l-8}" y="${y+4}" text-anchor="end" font-size="12" fill="#64748b">${Math.round(max*g/4)}</text>`}labels.forEach((x,i)=>{const xx=l+(labels.length===1?pw/2:i*pw/(labels.length-1));s+=`<text x="${xx}" y="${h-38}" text-anchor="middle" font-size="12" font-weight="700">${esc(x)}</text>`});series.forEach((z,si)=>{const pts=z.v.map((v,i)=>{const x=l+(labels.length===1?pw/2:i*pw/(labels.length-1)),y=top+ph-ph*v/max;return[x,y,v]});s+=`<polyline fill="none" stroke="${p[si%p.length]}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" points="${pts.map(x=>x[0]+','+x[1]).join(' ')}"/>`;pts.forEach(x=>s+=`<circle cx="${x[0]}" cy="${x[1]}" r="6" fill="#fff" stroke="${p[si%p.length]}" stroke-width="4"/><text x="${x[0]}" y="${x[1]-11}" text-anchor="middle" font-size="11" font-weight="700">${x[2]}</text>`)});return box(d.title,s+'</svg>')}
  function stimulus(q){if(!q)return'';if(q.passage)return `<div class="exam-stimulus passage-stimulus"><div style="line-height:1.75;white-space:pre-line">${esc(q.passage)}</div></div>`;const d=dataRows(q);if(!d)return'';if(d.type==='pie-chart')return pie(d);if(d.type==='bar-chart')return bars(d);if(d.type==='line-graph')return lines(d);return table(d)}
  function sameGroup(a,b){if(!a||!b)return false;const keys=['section','unit','category','subject'];const present=keys.filter(k=>String(a[k]??'')||String(b[k]??''));return present.length>0&&present.every(k=>String(a[k]??'')===String(b[k]??''))}
  function currentObj(){const h=card()?.querySelector('h2');if(!h)return null;const text=String(h.textContent||'').replace(/^\s*\d+\.\s*/,'');return findQuestion(text)}
  function repair(records){const c=card();if(!c)return;const q=currentObj();if(!q)return;const existing=c.querySelector('.exam-stimulus');if(existing){const fresh=stimulus(q);if(fresh){existing.outerHTML=fresh;lastStimulusHTML=c.querySelector('.exam-stimulus')?.outerHTML||''}else lastStimulusHTML=existing.outerHTML;lastObj=q;return}let removed='';for(const rec of records||[]){for(const n of rec.removedNodes||[]){if(n.nodeType===1){const x=n.matches?.('.exam-stimulus')?n:n.querySelector?.('.exam-stimulus');if(x)removed=x.outerHTML}}}if(removed)lastStimulusHTML=removed;if(lastStimulusHTML&&sameGroup(lastObj,q)&&!q.passage&&!q.data&&!q.figure){const h=c.querySelector('h2');if(h)h.insertAdjacentHTML('beforebegin',lastStimulusHTML)}lastObj=q}
  loadBank().then(()=>{const c=card();if(!c)return;let timer;new MutationObserver(records=>{clearTimeout(timer);timer=setTimeout(()=>repair(records),30)}).observe(c,{childList:true,subtree:true});setTimeout(()=>repair(),120)});
})();