const API='/.netlify/functions/set-api?action=';const $=s=>document.querySelector(s);let set=null,editing=-1,isNew=false;
const names={kharidar:'खरिदार',nasu:'नायब सुब्बा','sakha-adhikrit':'शाखा अधिकृत'};const token=()=>localStorage.getItem('nb_admin_token');const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(a,opt={}){const r=await fetch(API+a,{...opt,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token(),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function auth(){if(!token()){location.href='admin.html?returnTo='+encodeURIComponent('set-admin.html');return false}return true}
async function loadSets(){const d=await api('admin-list');const xs=d.sets.filter(x=>x.examId===$('#exam').value);$('#set').innerHTML=xs.map(x=>'<option value="'+esc(x.setId)+'">Set '+Number(x.setId)+' — '+x.questionCount+' प्रश्न</option>').join('');await loadSet()}
async function loadSet(){const d=await api('admin-get',{method:'POST',body:JSON.stringify({examId:$('#exam').value,setId:$('#set').value})});set=d.set;editing=-1;isNew=false;$('#editor').hidden=true;render()}
function render(){const term=$('#search').value.trim().toLowerCase();const qs=set.questions.map((q,i)=>({q,i})).filter(x=>!term||String(x.q.q||x.q.question).toLowerCase().includes(term));$('#questions').innerHTML=qs.map(({q,i})=>'<article class="q"><small>Q'+(i+1)+' · '+esc(q.section||'')+' · '+esc(q.unit||'')+'</small><p><b>'+esc(q.q||q.question)+'</b></p><p>सही: '+esc((q.options||[])[q.correct])+'</p><button class="btn btn-outline" onclick="editQ('+i+')">सम्पादन</button></article>').join('')||'<p>प्रश्न भेटिएन।</p>'}
function editQ(i){editing=i;isNew=false;const q=set.questions[i];$('#editor').hidden=false;$('#editor').innerHTML='<h3>Q'+(i+1)+' सम्पादन</h3><label>प्रश्न<textarea id="q">'+esc(q.q||q.question)+'</textarea></label><div class="grid">'+q.options.map((o,j)=>'<label>विकल्प '+String.fromCharCode(65+j)+'<input id="o'+j+'" value="'+esc(o)+'"></label>').join('')+'</div><label>सही विकल्प<select id="c">'+q.options.map((o,j)=>'<option value="'+j+'" '+(q.correct===j?'selected':'')+'>'+String.fromCharCode(65+j)+'</option>').join('')+'</select></label><label>व्याख्या<textarea id="e">'+esc(q.explanation||'')+'</textarea></label><label>Solution<textarea id="s">'+esc(q.solution||'')+'</textarea></label><button class="btn btn-primary" id="save">Set मा सुरक्षित गर्नुहोस्</button> <button class="btn" id="cancel">रद्द</button>';$('#cancel').onclick=()=>$('#editor').hidden=true;$('#save').onclick=save}
function newQ(){isNew=true;editing=-1;$('#editor').hidden=false;$('#editor').innerHTML='<h3>नयाँ प्रश्न बनाउनुहोस्</h3><p class="note">Set को प्रश्न संख्या र blueprint स्थिर राख्न नयाँ प्रश्नले छानिएको प्रश्नको slot लाई प्रतिस्थापन गर्छ। त्यसैले मुख्य परीक्षा Question Bank मा कुनै असर पर्दैन।</p><label>कुन प्रश्नको ठाउँमा नयाँ प्रश्न राख्ने<select id="replace">'+set.questions.map((x,i)=>'<option value="'+i+'">Q'+(i+1)+' — '+esc(String(x.q||x.question).slice(0,70))+'</option>').join('')+'</select></label><label>प्रश्न<textarea id="q"></textarea></label><div class="grid"><label>विकल्प A<input id="o0"></label><label>विकल्प B<input id="o1"></label><label>विकल्प C<input id="o2"></label><label>विकल्प D<input id="o3"></label></div><label>सही विकल्प<select id="c"><option value="0">A</option><option value="1">B</option><option value="2">C</option><option value="3">D</option></select></label><label>व्याख्या<textarea id="e"></textarea></label><label>Solution<textarea id="s"></textarea></label><button class="btn btn-primary" id="save">नयाँ प्रश्न Set मा सुरक्षित गर्नुहोस्</button> <button class="btn" id="cancel">रद्द</button>';$('#cancel').onclick=()=>$('#editor').hidden=true;$('#save').onclick=save}
async function save(){const idx=isNew?Number($('#replace').value):editing;const old=set.questions[idx];if(!old)return;const q={...old,id:isNew?old.id+'-new-'+Date.now():old.id,q:$('#q').value.trim(),options:[0,1,2,3].map(i=>$('#o'+i).value.trim()),correct:Number($('#c').value),explanation:$('#e').value.trim(),solution:$('#s').value.trim()};if(!q.q||q.options.some(x=>!x)){alert('प्रश्न र चारै विकल्प अनिवार्य छन्।');return}set.questions[idx]=q;try{await api('admin-save',{method:'POST',body:JSON.stringify({examId:$('#exam').value,setId:$('#set').value,set})});alert(isNew?'नयाँ प्रश्न Set मा सुरक्षित भयो। मुख्य परीक्षा परिवर्तन भएको छैन।':'Set Question Bank सुरक्षित भयो। मुख्य परीक्षा परिवर्तन भएको छैन।');$('#editor').hidden=true;isNew=false;editing=-1;render()}catch(e){set.questions[idx]=old;alert(e.message)}}
$('#exam').onchange=loadSets;$('#set').onchange=loadSet;$('#search').oninput=render;$('#newQuestion').onclick=newQ;$('#logout').onclick=()=>{localStorage.removeItem('nb_admin_token');location.href='admin.html'};if(auth())loadSets().catch(e=>alert(e.message));