const API='/.netlify/functions/set-api?action=';const $=s=>document.querySelector(s);let set=null,editing=-1;
const names={kharidar:'खरिदार',nasu:'नायब सुब्बा','sakha-adhikrit':'शाखा अधिकृत'};const token=()=>localStorage.getItem('nb_admin_token');const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(a,opt={}){const r=await fetch(API+a,{...opt,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token(),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function auth(){if(!token()){location.href='admin.html?returnTo='+encodeURIComponent('set-admin.html');return false}return true}
async function loadSets(){const d=await api('admin-list');const xs=d.sets.filter(x=>x.examId===$('#exam').value);$('#set').innerHTML=xs.map(x=>'<option value="'+esc(x.setId)+'">Set '+Number(x.setId)+' — '+x.questionCount+' प्रश्न</option>').join('');await loadSet()}
async function loadSet(){const d=await api('admin-get',{method:'POST',body:JSON.stringify({examId:$('#exam').value,setId:$('#set').value})});set=d.set;editing=-1;$('#editor').hidden=true;render()}
function render(){const term=$('#search').value.trim().toLowerCase();const qs=set.questions.map((q,i)=>({q,i})).filter(x=>!term||String(x.q.q||x.q.question).toLowerCase().includes(term));$('#questions').innerHTML=qs.map(({q,i})=>'<article class="q"><small>Q'+(i+1)+' · '+esc(q.section||'')+' · '+esc(q.unit||'')+'</small><p><b>'+esc(q.q||q.question)+'</b></p><p>सही: '+esc((q.options||[])[q.correct])+'</p><button class="btn btn-outline" onclick="editQ('+i+')">सम्पादन</button></article>').join('')||'<p>प्रश्न भेटिएन।</p>'}
function editQ(i){editing=i;const q=set.questions[i];$('#editor').hidden=false;$('#editor').innerHTML='<h3>Q'+(i+1)+' सम्पादन</h3><label>प्रश्न<textarea id="q">'+esc(q.q||q.question)+'</textarea></label><div class="grid">'+q.options.map((o,j)=>'<label>विकल्प '+String.fromCharCode(65+j)+'<input id="o'+j+'" value="'+esc(o)+'"></label>').join('')+'</div><label>सही विकल्प<select id="c">'+q.options.map((o,j)=>'<option value="'+j+'" '+(q.correct===j?'selected':'')+'>'+String.fromCharCode(65+j)+'</option>').join('')+'</select></label><label>व्याख्या<textarea id="e">'+esc(q.explanation||'')+'</textarea></label><label>Solution<textarea id="s">'+esc(q.solution||'')+'</textarea></label><button class="btn btn-primary" id="save">Set मा सुरक्षित गर्नुहोस्</button> <button class="btn" id="cancel">रद्द</button>';$('#cancel').onclick=()=>$('#editor').hidden=true;$('#save').onclick=save}
async function save(){const q=set.questions[editing];q.q=$('#q').value.trim();q.question=q.question?$('#q').value.trim():q.question;q.options=[0,1,2,3].map(i=>$('#o'+i).value.trim());q.correct=Number($('#c').value);q.explanation=$('#e').value.trim();q.solution=$('#s').value.trim();try{await api('admin-save',{method:'POST',body:JSON.stringify({examId:$('#exam').value,setId:$('#set').value,set})});alert('Set Question Bank सुरक्षित भयो। मुख्य परीक्षा परिवर्तन भएको छैन।');$('#editor').hidden=true;render()}catch(e){alert(e.message)}}
$('#exam').onchange=loadSets;$('#set').onchange=loadSet;$('#search').oninput=render;$('#logout').onclick=()=>{localStorage.removeItem('nb_admin_token');location.href='admin.html'};if(auth())loadSets().catch(e=>alert(e.message));