name: Handle Post

on:
  repository_dispatch:
    types: [new-post]

jobs:
  save_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Save Post to File
        run: |
          mkdir -p posts
          FILENAME="posts/post-$(date +%s).json"
          echo '${{ toJson(github.event.client_payload) }}' > "$FILENAME"

      - name: Commit & Push
        run: |
          git config user.name "Narayan Bhandari Bot"
          git config user.email "bhandarinarayan300@gmail.com"
          git add posts/
          git commit -m "नयाँ पोस्ट थपियो"
          git push
